[profile.default]
src = "src"
out = "out"
libs = ["../../dependencies"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
  "@openzeppelin/contracts/=../../dependencies/@openzeppelin-contracts-5.1.0/",
  "forge-std/=../../dependencies/forge-std/src/",
]

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
localhost = "http://127.0.0.1:8545"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

